[package]
name = "ryzenpmmeter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
appindicator3 = { version = "0.3.0", feature = ["original"] }
env_logger = "0.11.8"
gtk = "0.18.2"
log = "0.4.27"
rand = "0.9.1"
