[workspace]
members = [
	"libs/*",
	"themes/current",
	"app"
]
resolver = "3"

[workspace.dependencies]
# Core:
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.99"
libc = { version = "0.2.175" }
cluConstData = { version = "2.1.2", default-features = false, features = ["clufulltransmute"] }
include_tt = "1.1.0"